services:
  development:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    shm_size: '4gb'
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: 2G
        limits:
          memory: 8G
          cpus: "4"